git:
  submodules: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
    global:
      - COVERAGE=0

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
      env: COVERAGE=1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:

after_success:


after_failure:
  - cat storage/logs/laravel-`date +"%Y-%m-%d"`.log