git:
  submodules: false

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
      env: COVERAGE=1

env:
  global:
    - COVERAGE=0

before_script:
  - travis_retry composer self-update || true
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry composer run-script post-root-package-install
  - travis_retry composer run-script post-create-project-cmd
  - travis_retry composer run-script post-autoload-dump

script:
  - if [[ $COVERAGE = 1 ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.xml ; fi
  - if [[ $COVERAGE = 0 ]]; then ./vendor/bin/phpunit ; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

after_failure:
  - cat storage/logs/laravel-`date +"%Y-%m-%d"`.log